WARN[0000] init_model_failed                             modelCode=xgb_search_page_sort present version=-1 target version=v2
WARN[0000] init_model_failed                             modelCode=XGBSorterV2_detailpage_bottom_model_v1 present version=-1 target version=v4
WARN[0000] init_model_failed                             modelCode=order_share_XGBSorterV1 present version=-1 target version=v2
WARN[0000] init_model_failed                             modelCode=XGBSorterV2 present version=-1 target version=v4
WARN[0000] init_model_failed                             modelCode=XGBSorterV2_detailpage_bottom_model_v1 present version=v4 target version=v1
INFO[0000] init_model_success                            modelCode=XGBSorterV2 present version=v6 target version=v6
WARN[0000] init_model_failed                             modelCode=CH301012_model_6 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH303003_test present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301012_model_0 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=XGBSorterV3_4 present version=-1 target version=v2
WARN[0000] init_model_failed                             modelCode=XGBSorterV3 present version=v2 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301006_model_2 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301008_test_weight present version=v7 target version=v5
WARN[0000] init_model_failed                             modelCode=XGBSorterV3_1 present version=v14 target version=v8
WARN[0000] init_model_failed                             modelCode=CH303003_test_weight present version=v7 target version=v5
WARN[0000] init_model_failed                             modelCode=CH301008_test present version=-1 target version=v4
WARN[0000] init_model_failed                             modelCode=CH303004_test present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CategoryPageGlobalWeightedWithoutPair present version=-1 target version=v4
WARN[0000] init_model_failed                             modelCode=CH303004_test_weight_without_pair present version=-1 target version=v3
WARN[0000] init_model_failed                             modelCode=CH311001_test present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CategoryPageGlobalWeightedWithoutPair present version=v4 target version=v3
WARN[0000] init_model_failed                             modelCode=CategoryPageGlobal present version=v3 target version=v4
WARN[0000] init_model_failed                             modelCode=XGBSorterV2_2 present version=-1 target version=v4
WARN[0000] init_model_failed                             modelCode=wanshiweitest present version=v2 target version=v8
WARN[0000] init_model_failed                             modelCode=CH307001_category_weight present version=v7 target version=v5
WARN[0000] init_model_failed                             modelCode=CH301012_model_3 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CategoryPageGlobalWeighted present version=-1 target version=v7
WARN[0000] init_model_failed                             modelCode=CH301008_test_weight_without_pair present version=-1 target version=v3
INFO[0000] init_model_success                            modelCode=XGBOrcSorterV3_4 present version=v2 target version=v2
INFO[0000] init_model_success                            modelCode=CH301006_model_6 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=CH301006_model_0 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=XGBOrcSorterV3_6 present version=v2 target version=v2
INFO[0000] init_model_success                            modelCode=XGBSorterV3_1 present version=v15 target version=v15
WARN[0000] init_model_failed                             modelCode=CH302001_model0 present version=-1 target version=v3
INFO[0000] init_model_success                            modelCode=XGBSorterV3 present version=v2 target version=v2
WARN[0000] init_model_failed                             modelCode=CH305002 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301012_model_4 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301012_model_all present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301006_model_3 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301006_model_1 present version=-1 target version=v1
INFO[0000] init_model_success                            modelCode=CH301008_test_weight present version=v6 target version=v6
INFO[0000] init_model_success                            modelCode=CategoryPageGlobalWeighted present version=v8 target version=v8
INFO[0000] init_model_success                            modelCode=detailpage_share_v2 present version=v1 target version=v1
WARN[0000] init_model_failed                             modelCode=XGBSorterV2 present version=v6 target version=v34
WARN[0000] init_model_failed                             modelCode=XGBSorterV3_1 present version=v15 target version=v14
WARN[0000] init_model_failed                             modelCode=CH301020 present version=-1 target version=v1
INFO[0000] init_model_success                            modelCode=XGBSorterV999 present version=v10 target version=v10
WARN[0000] init_model_failed                             modelCode=XGB_UIPS_OZ present version=-1 target version=v1
INFO[0000] init_model_success                            modelCode=CH307001_category_weight present version=v6 target version=v6
WARN[0000] init_model_failed                             modelCode=CH307001_category_weight present version=v6 target version=v7
WARN[0000] init_model_failed                             modelCode=CategoryPageGlobal present version=-1 target version=v3
WARN[0000] init_model_failed                             modelCode=CH303001_test present version=-1 target version=v3
WARN[0000] init_model_failed                             modelCode=CH303003_test_weight present version=-1 target version=v7
INFO[0000] init_model_success                            modelCode=CH301012_model_5 present version=v1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH305001 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301006_model_5 present version=-1 target version=v1
INFO[0000] init_model_success                            modelCode=CH301006_model_4 present version=v1 target version=v1
WARN[0000] init_model_failed                             modelCode=XGBSorterV3_2 present version=-1 target version=v2
WARN[0000] init_model_failed                             modelCode=CH307001_category_weight_without_pair present version=-1 target version=v4
WARN[0000] init_model_failed                             modelCode=XGBSorterV999 present version=v10 target version=v9
WARN[0000] init_model_failed                             modelCode=CH303001_test present version=v3 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301001_test_model0 present version=-1 target version=v3
INFO[0000] init_model_success                            modelCode=wanshiweitest present version=v2 target version=v2
WARN[0000] init_model_failed                             modelCode=CH307001_category_weight_without_pair present version=v4 target version=v3
WARN[0000] init_model_failed                             modelCode=CH303001_test_event present version=-1 target version=v2
WARN[0000] init_model_failed                             modelCode=CH301008_test_weight present version=-1 target version=v7
WARN[0000] init_model_failed                             modelCode=CH303001_test present version=v1 target version=v2
WARN[0000] init_model_failed                             modelCode=xgb_home_page_sort present version=-1 target version=v2
INFO[0000] init_model_success                            modelCode=CH301012_model_2 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=CH305003 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=XGBSorterV2 present version=v32 target version=v32
INFO[0000] init_model_success                            modelCode=HomePageXGBSorterV1 present version=v31 target version=v31
INFO[0000] init_model_success                            modelCode=detailpage_share_v1 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=DetailPageMiddleXGBSorterV1 present version=v7 target version=v7
INFO[0000] init_model_success                            modelCode=XGBSorterV2_2 present version=v5 target version=v5
INFO[0000] init_model_success                            modelCode=XGBSorterV4_2 present version=v1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH303004_test_weight_without_pair present version=v3 target version=v4
INFO[0000] init_model_success                            modelCode=CH301012_model_1 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=CH305008 present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=XGBCtxTime present version=v1 target version=v1
INFO[0000] init_model_success                            modelCode=CH307001_category present version=v3 target version=v3
INFO[0000] init_model_success                            modelCode=order_share_XGBSorterV1 present version=v3 target version=v3
WARN[0000] init_model_failed                             modelCode=CH303002_test present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=XGB_UICPS_OZ present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=XGBSorterV2 present version=v32 target version=v5
WARN[0000] init_model_failed                             modelCode=XGBSorterV4_1 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH305009 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=detailpage_share_v1_time present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=detailpage_purchase_now_xgb_v3_model present version=-1 target version=v2
WARN[0000] init_model_failed                             modelCode=detailpage_add_cart_v1 present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH301008_test_weight_without_pair present version=v3 target version=v4
WARN[0000] init_model_failed                             modelCode=CH303003_test_weight present version=v5 target version=v6
WARN[0000] init_model_failed                             modelCode=HomePageXGBSorterV1 present version=v31 target version=v33
WARN[0000] init_model_failed                             modelCode=xgb_detail_page_middle_sort present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH307001_category present version=v3 target version=v4
WARN[0000] init_model_failed                             modelCode=XGBSorterV3_1 present version=v8 target version=v1
WARN[0000] init_model_failed                             modelCode=CH302008_test present version=-1 target version=v1
WARN[0000] init_model_failed                             modelCode=CH303002_test present version=v1 target version=v2